language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install . --use-mirrors"
  - "pip install -r test_requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests
